package com.amazonaws.lambda.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Sample")
public class DynamoTable {
	
	private int id;
    private String payload;
    
    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public int getId() { return id; }
    public void setId(int i) { this.id = i; } 

    @DynamoDBAttribute(attributeName="Payload")
    public String getPayload() { return this.payload; }
    public String setPayload(String payload) { return this.payload = payload; }    
   

}
